-- luacheck configuration for the addon (dev-only; not shipped, see .pkgmeta).
-- Run: luacheck . (Mechanic's desktop/bin/luacheck.exe, or any luacheck 0.23+)
std = "lua51"
max_line_length = false
unused = false   -- 132 unused locals today; turn on when tidying
exclude_files = { "tests/**", "scripts/**", ".local/**", "**/Libs/**" }
-- WoW API and Blizzard UI globals the addon reads (collected 2026-09-28 from the code;
-- add new ones here when luacheck reports "accessing undefined variable").
read_globals = {
    "Auctionator",
    "C_AddOns",
    "C_AuctionHouse",
    "C_Bank",
    "C_Container",
    "C_CurrencyInfo",
    "C_EquipmentSet",
    "C_Heirloom", "C_Item",
    "C_MountJournal",
    "C_PetJournal",
    "C_PlayerInteractionManager",
    "C_QuestLog",
    "C_Timer",
    "C_TooltipInfo",
    "C_ToyBox",
    "C_TransmogCollection",
    "ChatFontNormal",
    "ClearCursor",
    "CreateFrame",
    "DeleteCursorItem",
    "ERR_VENDOR_DOESNT_BUY",
    "EXPANSION_NAME0",
    "EXPANSION_NAME1",
    "EXPANSION_NAME10",
    "EXPANSION_NAME11",
    "EXPANSION_NAME2",
    "EXPANSION_NAME3",
    "EXPANSION_NAME4",
    "EXPANSION_NAME5",
    "EXPANSION_NAME6",
    "EXPANSION_NAME7",
    "EXPANSION_NAME8",
    "EXPANSION_NAME9",
    "Enum",
    "EnumerateFrames",
    "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_OnVerticalScroll",
    "FauxScrollFrame_Update",
    "GameTooltip", "GetQuestLogSpecialItemInfo", "GameTooltip_ShowCompareItem",
    "GetAverageItemLevel",
    "GetBuildInfo",
    "GetCoinTextureString",
    "GetCursorInfo",
    "GetInboxHeaderInfo",
    "GetInboxNumItems",
    "GetInventoryItemID",
    "GetInventoryItemLink",
    "GetItemInfo",
    "GetMaxLevelForLatestExpansion",
    "GetMaxLevelForPlayerExpansion",
    "GetMoney",
    "GetNormalizedRealmName",
    "GetProfessionInfo",
    "GetProfessions",
    "GetRealmName",
    "GetTime",
    "ITEM_ACCOUNTBOUND",
    "ITEM_ACCOUNTBOUND_UNTIL_EQUIP",
    "ITEM_BNETACCOUNTBOUND",
    "ITEM_CLASSES_ALLOWED",
    "ITEM_SET_BONUS",
    "ITEM_SOULBOUND",
    "ITEM_SPELL_KNOWN",
    "ITEM_UPGRADE_TOOLTIP_FORMAT_STRING",
    "InCombatLockdown",
    "ItemLocation",
    "LE_EXPANSION_BATTLE_FOR_AZEROTH",
    "LE_EXPANSION_BURNING_CRUSADE",
    "LE_EXPANSION_CATACLYSM",
    "LE_EXPANSION_CLASSIC",
    "LE_EXPANSION_DRAGONFLIGHT",
    "LE_EXPANSION_LEGION",
    "LE_EXPANSION_MIDNIGHT",
    "LE_EXPANSION_MISTS_OF_PANDARIA",
    "LE_EXPANSION_SHADOWLANDS",
    "LE_EXPANSION_WARLORDS_OF_DRAENOR",
    "LE_EXPANSION_WAR_WITHIN",
    "LE_EXPANSION_WRATH_OF_THE_LICH_KING",
    "LibStub",
    "Minimap",
    "PlayerHasToy",
    "RETRIEVING_ITEM_INFO",
    "TSM_API",
    "TooltipDataProcessor",
    "UIParent",
    "UISpecialFrames",
    "UnitClass",
    "UnitClassBase",
    "UnitFullName",
    "UnitLevel",
    "UnitName",
    "bit",
    "date",
    "geterrorhandler",
    "issecretvalue",
    "seterrorhandler",
    "time",
    "tinsert",
    "wipe",
}
-- Globals the addon defines.
globals = { "ICantEvenRightNowDB", "SLASH_ICANTEVEN1", "SLASH_ICANTEVEN2", "SlashCmdList" }
